### ISSUE TITLE
No effective change - for running tests update to use docker postgis and application-test.yml

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/ebean-postgis#2]
- Uses the `mdillon/postgis` docker image which has postgis extension installed.
- Container name `postgis10`
- Use appropriate driver and url 

```yml
ebean:
  geometrySRID: 4674

  test:
#    useDocker: false
#    shutdown: stop # stop | remove
    platform: postgres
    ddlMode: none # none | dropCreate | create | migration | createOnly | migrationDropCreate
    dbName: mygisapp
    postgres:
      containerName: postgis10
      image: mdillon/postgis
      extensions: postgis
      url: jdbc:postgresql_lwgis://127.0.0.1:6432/mygisapp
      driver: org.postgis.DriverWrapperLW

```
